### ISSUE TITLE
是否能够增添对于群聊用户中性别及地区的收集？

### ISSUE THREAD

**Issue by CrispyChickenNuggets** [RunDebugCode/WeChatGroup#1]
我运行了你发布的文件，确实可以按需求拿到群聊成员的昵称及备注

**Comment by RunDebugCode** [comment]
抱歉，软件基于窗口捕获获取信息，性别和地区需要进一步打开才能获取（也就是需要控制点击头像打开），这一步暂时做不到，需要其他方法实现
